export const GAMES = [
  {
    id: "valorant",
    label: "Valorant",
    icon: "◆",
    accent: "#E63960",
    rankLabel: "Current rank",
    ranks: [
      "Iron",
      "Bronze",
      "Silver",
      "Gold",
      "Platinum",
      "Diamond",
      "Ascendant",
      "Immortal",
      "Radiant",
    ],
    levelLabel: "Account level",
    itemsLabel: "Skin names",
    itemsPlaceholder: "Comma-separated, e.g. Reaver Vandal, Glitchpop Phantom, Prime Knife",
  },
  {
    id: "clash_of_clans",
    label: "Clash of Clans",
    icon: "▲",
    accent: "#F2A93B",
    rankLabel: "Town Hall level",
    ranks: [
      "Town Hall 9",
      "Town Hall 10",
      "Town Hall 11",
      "Town Hall 12",
      "Town Hall 13",
      "Town Hall 14",
      "Town Hall 15",
      "Town Hall 16",
      "Town Hall 17",
    ],
    levelLabel: "Experience level",
    itemsLabel: "Maxed heroes / notable items",
    itemsPlaceholder: "Comma-separated, e.g. Max Barbarian King, Max Archer Queen, Champion League",
  },
  {
    id: "bgmi",
    label: "BGMI",
    icon: "●",
    accent: "#FF8A3D",
    rankLabel: "Current tier",
    ranks: [
      "Bronze",
      "Silver",
      "Gold",
      "Platinum",
      "Diamond",
      "Crown",
      "Ace",
      "Ace Master",
      "Ace Dominator",
      "Conqueror",
    ],
    levelLabel: "Account level",
    itemsLabel: "Notable skins",
    itemsPlaceholder: "Comma-separated, e.g. Glacier M416, Mythic outfit, Pharaoh X-Suit",
  },
  {
    id: "free_fire",
    label: "Free Fire",
    icon: "🔥",
    accent: "#FF4500",
    rankLabel: "Current rank",
    ranks: [
      "Bronze",
      "Silver",
      "Gold",
      "Platinum",
      "Diamond",
      "Heroic",
      "Grandmaster",
    ],
    levelLabel: "Account level",
    itemsLabel: "Notable bundles / gun skins",
    itemsPlaceholder: "Comma-separated, e.g. Cobra MP40, Hip Hop Bundle, Evo Gun, Criminal Bundle",
  },
];

export function getGameConfig(gameId) {
  return GAMES.find((g) => g.id === gameId) || GAMES[0];
}
