// Fallback data shown on /buy or /rent if database has no accounts yet.
export const ACCOUNTS = [
  {
    id: "acc_1",
    game: "valorant",
    title: "Immortal 2 -- Full Ready-Up Skin Vault",
    rank: "Immortal 2",
    level: 214,
    region: "India",
    skinNames: ["Reaver Vandal", "Glitchpop Phantom", "Prime 2.0 Knife", "Ion Sheriff"],
    price: 4200,
    listingType: "buy",
    seller: "vantablade",
    verified: true,
  },
  {
    id: "acc_2",
    game: "bgmi",
    title: "Diamond Tier -- Glacier + Mythic Vault",
    rank: "Diamond",
    level: 68,
    region: "India",
    skinNames: ["Glacier M416", "Mythic Forever Suit"],
    price: 3400,
    listingType: "rent",
    rentPeriodDays: 30,
    seller: "duskrunner",
    verified: true,
  },
  {
    id: "acc_3",
    game: "clash_of_clans",
    title: "Town Hall 14 -- Max Heroes, Champion League",
    rank: "Town Hall 14",
    level: 210,
    region: "India",
    skinNames: ["Max Barbarian King", "Max Archer Queen", "Max Grand Warden", "Champion League"],
    price: 6800,
    listingType: "emi",
    emiMonths: 3,
    seller: "nightshade07",
    verified: true,
  },
  {
    id: "acc_4",
    game: "clash_of_clans",
    title: "Town Hall 11 -- Starter Base, Clean History",
    rank: "Town Hall 11",
    level: 130,
    region: "India",
    skinNames: ["Master League"],
    price: 2600,
    listingType: "buy",
    seller: "echo_ind",
    verified: false,
  },
  {
    id: "acc_5",
    game: "valorant",
    title: "Radiant -- Champions Bundle, OG Titles",
    rank: "Radiant",
    level: 341,
    region: "India",
    skinNames: ["Champions Vandal", "Champions Knife", "RGX Phantom", "Reaver Operator"],
    price: 9800,
    listingType: "buy",
    seller: "vantablade",
    verified: true,
  },
  {
    id: "acc_6",
    game: "bgmi",
    title: "Crown Tier -- Budget Smurf, Fresh Season",
    rank: "Crown",
    level: 34,
    region: "India",
    skinNames: ["Recon Vector"],
    price: 3100,
    listingType: "rent",
    rentPeriodDays: 15,
    seller: "duskrunner",
    verified: true,
  },
  {
    id: "acc_7",
    game: "valorant",
    title: "Immortal 1 -- Reaver 2.0 Full Set",
    rank: "Immortal 1",
    level: 201,
    region: "India",
    skinNames: ["Reaver 2.0 Vandal", "Reaver 2.0 Knife", "Reaver 2.0 Sheriff"],
    price: 8400,
    listingType: "emi",
    emiMonths: 2,
    seller: "nightshade07",
    verified: true,
  },
  {
    id: "acc_8",
    game: "bgmi",
    title: "Ace Tier -- Fresh Account, Region Locked",
    rank: "Ace",
    level: 21,
    region: "India",
    skinNames: [],
    price: 3900,
    listingType: "buy",
    seller: "echo_ind",
    verified: false,
  },
  {
    id: "acc_9",
    game: "free_fire",
    title: "Grandmaster -- Cobra MP40 + Hip Hop Bundle",
    rank: "Grandmaster",
    level: 72,
    region: "India",
    skinNames: ["Cobra MP40", "Hip Hop Bundle", "Poker MP40", "Evo Gun"],
    price: 4500,
    listingType: "rent",
    rentPeriodDays: 7,
    seller: "fireking99",
    verified: true,
  },
  {
    id: "acc_10",
    game: "free_fire",
    title: "Heroic Tier -- Criminal Bundle + Max Evo Skins",
    rank: "Heroic",
    level: 65,
    region: "India",
    skinNames: ["Red Criminal Bundle", "AK47 Blue Flame Draco", "M1887 Tropical"],
    price: 5200,
    listingType: "buy",
    seller: "blaze_ff",
    verified: true,
  },
];

export const BUDGET_TIERS = [
  { id: "3-4k", label: "₹3k – ₹4k", min: 3000, max: 4000 },
  { id: "5-7k", label: "₹5k – ₹7k", min: 5000, max: 7000 },
  { id: "8-10k", label: "₹8k – ₹10k", min: 8000, max: 10000 },
];

export const LISTING_TYPES = [
  { id: "buy", label: "Buy" },
  { id: "rent", label: "Rent" },
  { id: "emi", label: "EMI" },
];
